'INPUTS'='/home/chris/science/experiments/2023/cd1a-new-docking/inputs'
'OUTPUTS'='/home/chris/science/experiments/2023/cd1a-new-docking/outputs'
'CONFORMER_COUNT'=50
'GNINA_PATH'='/home/chris/science/tools/gnina'